matrix:
  include:
    - language: cpp
      before_script:
        - cd client
      script:
        - ./build.sh && ./test.sh 

    - language: go
      go:
        - "1.9"
      before_script:
        - cd backend
      script:
        - go build && go test 

script: 
  - ./done-hook.sh
