stages:
  - test
  - deploy

matrix:
  include:
    - stage: test
    - language: cpp
      before_script:
        - cd client
      script:
        - ./build.sh && ./test.sh 

    - stage: test
    - language: go
      go:
        - "1.9"
      before_script:
        - cd backend
      script:
        - go build && go test 

- stage: deploy
  script: echo script && ./done-hook.sh
